### ISSUE TITLE
How to use the pretrained model to analyse emotions in Web camera? 

### ISSUE THREAD

**Issue by Sarah-em** [Bodhis4ttva/LHC_Net#2]
How to use the trained model to analyze emotions in Web camera? 
Can you please give me guidance...thanks in advance.

**Comment by Bodhis4ttva** [comment]
You mean real time?

**Comment by Sarah-em** [comment]
> You mean real time?

Yes.

**Comment by Bodhis4ttva** [comment]
There are 2 main problems:

1. This model was originally designed only to compete in FER2013 in a **static** way. It's a little too heavy to be used for real time applications and TTA is definitely not suitable for that purpose, it's too slow.
2. This repository was only intended to allow replicating the test environment and performances we described in the paper.

Despite 1. and 2. I would give it a try without TTA but, unfortunately, I don't have any script to feed the model with real time data from a webcam. I quickly created for you a starting point to try implement this interface yourself. You'll find in the repository a script called Gen_Inference.py provided with some instructions on how to build the proper input pipeline. Executing the script will result in the model loaded and ready to be inferenced on a numpy array. Also the libraries and functions needed to inference it will be loaded. You'll need to code the data feed part which will provide this array.

Please be sure to follow the instructions in the script for the proper input pre-processing:
# INPUT PIPEPLINE
# the input x must be a numpy array with the following requisites:
# 1. greyscale image with shape [batch_size, 224, 224, 3]
# 2. 3 channels (the same greyscale channel is repeated in all 3 channels, all 3 channels are equal)
# 3. bilinear method is recommended to resize images to the target shape (224, 224)
# 4. every pixel in the range [0, 255]
# 5. an average pixel intensity of 129 is recommended. Consider adjusting image brightness.
